language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run build && node scripts/md2json.js
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "blog.beeceej.com"
    region: us-east-1
    local_dir: ./dist/
    skip_cleanup: true
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "static.bucket.test"
    region: us-east-1
    local_dir: ./posts/json
    skip_cleanup: true
  

on:
  branch: master