language: node_js

# test on two node.js versions: 0.6 and 0.8
node_js:
  - "6"

install: npm install
script: npm run build && node scripts
deploy:
  provider: s3
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRETE_ACCESS_KEY
  bucket: "blog.beeceej.com"
  region: us-east-1
  local_dir: dist