language: node_js
node_js:
  - 'stable'
script:
  - npm run build
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: 'blog.beeceej.com'
    region: us-east-1
    local_dir: ./dist/
    skip_cleanup: true
on:
  branch: master
